name: Deploy Shopify Theme (Debug)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Shopify CLI
        run: |
          echo "📦 Installing Shopify CLI..."
          npm install -g @shopify/cli@latest
          echo "✅ Shopify CLI version:"
          shopify version

      - name: Debug - List theme files
        run: |
          echo "📁 Repository contents:"
          ls -la
          echo "📁 Checking for theme structure:"
          ls -la templates/ || echo "No templates folder"
          ls -la assets/ || echo "No assets folder"
          ls -la sections/ || echo "No sections folder"

      - name: Test Shopify Connection
        env:
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_API_PASSWORD: ${{ secrets.SHOPIFY_API_PASSWORD }}
        run: |
          echo "🔍 Testing connection to Shopify..."
          echo "Store URL: $SHOPIFY_STORE_URL"
          shopify theme list --store "$SHOPIFY_STORE_URL" --password "$SHOPIFY_API_PASSWORD" || {
            echo "❌ Failed to connect to Shopify. Check your store URL and password."
            exit 1
          }

      - name: Push Theme to Shopify
        env:
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_API_PASSWORD: ${{ secrets.SHOPIFY_API_PASSWORD }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
        run: |
          echo "🚀 Pushing theme to Shopify..."
          echo "Store: $SHOPIFY_STORE_URL"
          echo "Theme ID: $SHOPIFY_THEME_ID"

          shopify theme push \
            --store "$SHOPIFY_STORE_URL" \
            --password "$SHOPIFY_API_PASSWORD" \
            --theme "$SHOPIFY_THEME_ID" \
            --allow-live \
            --verbose

      - name: Publish Shopify Theme
        env:
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_API_PASSWORD: ${{ secrets.SHOPIFY_API_PASSWORD }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
        run: |
          echo "🎉 Publishing theme..."
          shopify theme publish \
            --store "$SHOPIFY_STORE_URL" \
            --password "$SHOPIFY_API_PASSWORD" \
            --theme "$SHOPIFY_THEME_ID" \
            --force
